config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'
  get ':page', to: 'welcome#show', constraints: { page: /contact/ }, as: :page
  get 'callback', to: 'sessions#create'
  post 'webhook', to: 'rebases#create', as: :webhook

  resources :projects do
    resource :test_message, only: :create, controller: 'projects/test_messages'
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :rebase, only: [:edit, :update], controller: :rebases
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/ssh.rb
module SSH
  SSH_CONFIG = %(
    Host %{name} github.com
    Hostname github.com
    IdentityFile ~/.ssh/id_rsa.%{name}
  ).freeze

  def generate_ssh
    ssh_path = File.expand_path("#{ENV['key_path']}/id_rsa.#{name.parameterize}")
    return if File.file?(ssh_path)
    Timeout.timeout(3) do
      `ssh-keygen -t rsa -N '' -f #{ENV['key_path']}/id_rsa.#{name.parameterize}`
      config = SSH_CONFIG % { name: name.parameterize }
      `echo "#{config}" >> #{ENV['key_path']}/config`
    end
  end
end

app/models/rebase.rb
class Rebase < ApplicationRecord
  belongs_to :repository, class_name: 'Repo', foreign_key: :repo, primary_key: :name

  validates :base, :head, :sha, presence: true

  delegate :user, to: :repository
  delegate :name, to: :repository, prefix: true

  def update_with_payload(attributes)
    initialize_payload_value(attributes[:payload])
    assign_attributes(attributes.except(:payload))
    save
  end

  def self.update_pull_state(payload)
    rebase = find_by_github_id(payload['pull_request']['id'])
    rebase.update_attributes(state: payload['pull_request']['state']) if rebase
  end

  private

  def initialize_payload_value(payload)
    self.repo = payload['repository']['full_name']
    pr = payload['pull_request']
    self.base = pr['base']['ref']
    self.head = pr['head']['ref']
    self.sha = pr['head']['sha']
    self.state = pr['state']
    self.number = pr['number']
    self.title = pr['title']
  end
end

app/models/repo.rb
class Repo < ApplicationRecord
  include SSH

  belongs_to :user
  has_many :rebases, primary_key: :name, foreign_key: :repo, class_name: 'Rebase', dependent: :destroy

  validates :name, :ssh, presence: true, uniqueness: true

  before_validation :set_github_data, on: :create
  after_create :generate_ssh, :init_project
  after_destroy :clean_project

  private

  def set_github_data
    self.ssh = git_repo['ssh_url']
    self.collaborators = git_collaborators
  end

  def init_project
    user.github.create_hook(name, 'web', { url: webhook }, { events: %w[push pull_request] }) unless hook_url
    user.github.add_deploy_key(name, 'ProjectR', ssh_key) unless deploy_key
  end

  def clean_project
    DynamicWorker.call(name, CleanerWorker, name, user.id)
  end

  def git_repo
    @git_repo ||= user.github.repo(name)
  end

  def git_collaborators
    @git_collaborators ||= user.github.collaborators(name).map(&:id)
  end

  def github_hooks
    @github_hooks ||= user.github.hooks(name)
  end

  def github_dkeys
    @github_dkeys ||= user.github.deploy_keys(name)
  end

  def webhook
    @webhook ||= Rails.application.routes.url_helpers.webhook_url(host: ENV['host'], port: nil)
  end

  def hook_url
    github_hooks.any? { |h| h['config']['url'] == webhook }
  end

  def deploy_key
    github_dkeys.any? { |d| d['key'] == ssh_key.split[0..1].join(' ') }
  end

  def ssh_key
    @ssh_key ||= `cat #{ENV['key_path']}/id_rsa.#{name.parameterize}.pub`.strip
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :repos, dependent: :delete_all
  has_many :rebases, through: :repos

  def update_with_github(info, token)
    self.name = info.name
    self.username = info.login
    self.email = info.email
    self.avatar = info.avatar_url
    self.token = token
    save
  end

  def github
    @github ||= Octokit::Client.new(access_token: token, per_page: 100)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def github
    @github ||= Octokit::Client.new(
      client_id: ENV['github_token'],
      client_secret: ENV['github_secret']
    )
  end

  def require_user
    head 404 unless current_user
  end
end

app/controllers/projects/test_messages_controller.rb
class Projects::TestMessagesController < ApplicationController
  def create
    DynamicWorker.call(
      params[:project_id],
      SenderWorker,
      repo: params[:project_id],
      channel_url: params[:channel_url],
      status: 'test'
    )
    head :ok
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :check_repo, only: :show

  def index
    @repos = current_user.github.repos.select { |a| a.permissions.admin }
  end

  def update
    repo.update(repo_params)
  end

  def create
    @repo = current_user.repos.build(name: params[:id])
    if @repo.valid? && @repo.save
      DynamicWorker.call(@repo.name, RefresherWorker, @repo.name)
      render :show
    else
      @errors = @repo.errors
    end
  end

  def destroy
    repo.destroy
    redirect_to projects_path
  end

  private

  def repo
    @repo ||= current_user.repos.find_by!(name: params[:id])
  end
  helper_method :repo

  def pulls
    @pulls ||= repo.rebases.where(state: 'open').order('created_at')
  end
  helper_method :pulls

  def check_repo
    send :create unless current_user.repos.any? { |r| r.name == params[:id] }
  end

  def repo_params
    params.require(:repo).permit(:auto_rebase, :channel_url)
  end
end

app/controllers/rebases_controller.rb
class RebasesController < ApplicationController
  EVENTS = %w[push pull_request].freeze
  ACTIONS = %w[opened reopened synchronize edited].freeze

  skip_before_action :verify_authenticity_token, only: :create
  skip_before_action :require_user, only: :create

  before_action :check_for_access, only: :update

  def create
    send(event) if EVENTS.include?(event)
    head 200
  end

  def update
    PusherWorker.new.perform(params[:id])
    respond_to do |format|
      format.html { redirect_to project_path(rebase.repo) }
      format.js
    end
  end

  private

  def event
    @event ||= request.env['HTTP_X_GITHUB_EVENT']
  end

  def push
    `rm -rf #{repo_name}` unless payload['deleted']
    DynamicWorker.call(repo_name, RefresherWorker, repo_name, base)
  end

  def pull_request
    if ACTIONS.include?(payload['action'])
      DynamicWorker.call(repo_name, RebaserWorker, payload)
    else
      DynamicWorker.call(repo_name, StateUpdaterWorker, payload)
    end
  end

  def repo_name
    @repo_name ||= payload['repository']['full_name']
  end

  def base
    @base ||= payload['ref'].split('/').last
  end

  def rebase
    @rebase ||= Rebase.find(params[:id])
  end

  def check_for_access
    head :unprocessable_entity unless access
  end

  def access
    repo = Repo.find_by(name: rebase.repo)
    repo.collaborators.include?(current_user.github_id)
  end

  def payload
    JSON.parse(params[:payload])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user

  def create
    user = User.where(github_id: github_id).first_or_initialize
    user.update_with_github(
      github_user,
      token
    )
    session[:user_id] = user.id
    redirect_to projects_path
  end

  def destroy
    session.delete :auth_token
    reset_session
    redirect_to root_path
  end

  private

  def token
    @token ||= github.exchange_code_for_token(params[:code])['access_token']
  end

  def github_id
    @github_id ||= github_user.id
  end

  def github_user
    @github_user ||= Octokit::Client.new(access_token: token).user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_user
  before_action :require_guest, only: :index

  layout 'landing'

  def show
    render params[:page]
  end

  private

  def require_guest
    redirect_to projects_path if current_user
  end
end

app/views/layouts/_schema.html.slim
div itemscope="" itemtype="http://schema.org/WebSite"
  link href="https://projectr.io/" itemprop="url" /

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectR. GitHub tool to keep your commit's history clean</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/landing.html.slim
doctype 5
html
  head
    title ProjectR
    = stylesheet_link_tag 'landing', media: 'all'
    = csrf_meta_tags
    meta name = "viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta name = 'description' content=t('meta.description')
    meta property = "fb:app_id" content="myid"
    meta property = "og:url" content="https://projectr.io/"
    meta property = "og:type" content="website"
    meta property = "og:title" content="ProjectR"
    meta property = "og:description" content="ProjectR is github tool helping you to keep your commit's history clean"
    meta property = "og:image" content="https://imgur.com/I91XEIk"

  body
    .body-schema = render 'layouts/schema'
    = yield

app/views/projects/_pull.html.slim
li.pull-list__item
  div id = "pull_#{pull.id}" class="pl-#{pull.status}"
  .item-title
    = pull.title
  - if pull.status == 'failure'
    .action
      = link_to :rebase, rebase_path(pull), method: :patch, remote: true, id: 'link_rebase'
      .spinner#spinner
        = inline_svg 'spinner.svg'

app/views/projects/index.html.slim
= link_to sessions_path, method: :delete do
  = inline_svg 'logout.svg', class: 'logout'
.head
  = inline_svg 'logo-title.svg', class: 'title'
ul.list
  - @repos.each do |r|
    = link_to project_path(r.full_name), class: 'link' do
      li.list__item
        .list__title
          = r.full_name
        .created
          => "created #{time_ago_in_words(r.created_at)} ago"

app/views/projects/show.html.slim
.repository
  .channel-form
    = form_for repo, url: project_path, method: :patch, remote: true do |f|
      = f.text_field :channel_url, class: 'channel-url', placeholder: t('placeholder.webhook')
      br
      = f.submit :save, data: { disable_with: 'Please wait...' }, class: 'channel-button'
      = link_to t(:test), project_test_message_path(repo.name), class: 'channel-button', id: 'test_channel'
  .repository-head
    .repository-title
      = repo.name
    .repository-form
      = form_for repo, url: project_path, method: :patch, remote: true do |f|
        .flatCheckbox
          = f.check_box :auto_rebase, class: 'auto-rebase'
          label for='repo_auto_rebase'
          div
      = link_to project_path(repo.name), method: :delete, class: 'link-delete' do
        = inline_svg 'trash.svg', class: 'delete'
  ul.pull-list
    = render partial: 'pull', collection: pulls

app/views/rebases/edit.slim
h1 Rebase

= link_to :Rebase, rebase_path, method: :patch

app/views/welcome/contact.slim
.contacts
  = inline_svg 'projectr.svg', class: 'logo'

  .description
    p = t(:slack_info)

  .contacts-container
    .contacts-section
      = inline_svg 'telephone.svg', class: 'icon'
      .information = t('.phone')
    .contacts-section
      = inline_svg 'email.svg', class: 'icon'
      .information = t('.email')

app/views/welcome/index.slim
.version
.icons-block
  a href='https://plus.google.com/u/0/+ActivebridgeTeam' target='_blank'
    = inline_svg 'google-plus.svg', class: 'social-icon google-plus'

  a href='https://www.linkedin.com/company/active-bridge' target='_blank'
    = inline_svg 'linkedin.svg', class: 'social-icon linkedin'

  a href='https://www.facebook.com/ActiveBridgeTeam' target='_blank'
    = inline_svg 'facebook.svg', class: 'social-icon facebook'

  a href='https://twitter.com/ActiveBridge' target='_blank'
    = inline_svg 'twitter.svg', class: 'social-icon twitter'

= inline_svg 'left_sticks.svg', class: 'left-sticks'
= inline_svg 'right_sticks.svg', class: 'right-sticks'
.main
  = inline_svg 'projectr.svg', class: :logo
  br
  => inline_svg 'ugly.svg', class: 'history ugly'
  span.to>
  = inline_svg 'clean.svg', class: 'history clean'
.slack-block
  = link_to Octokit.authorize_url(ENV['github_token'], scope: 'repo,user:email'), title: 'Start NOW', class: 'start-button' do
    = inline_svg 'start_button.svg', class: 'start-button-svg'
  = inline_svg 'slack_title.svg', class: 'slack-title'
  p = t(:slack_info)
  a href='https://slack.com/oauth/pick_reflow?scope=incoming-webhook&client_id=4033344265.85008077684' target='_blank'
    = inline_svg 'slack_button.svg', class: 'slack-button'

  .footer-icons-block
    a href='https://plus.google.com/u/0/+ActivebridgeTeam' target='_blank'
      = inline_svg 'google-plus.svg', class: 'social-icon google-plus'

    a href='https://www.linkedin.com/company/active-bridge' target='_blank'
      = inline_svg 'linkedin.svg', class: 'social-icon linkedin'

    a href='https://www.facebook.com/ActiveBridgeTeam' target='_blank'
      = inline_svg 'facebook.svg', class: 'social-icon facebook'

    a href='https://twitter.com/ActiveBridge' target='_blank'
      = inline_svg 'twitter.svg', class: 'social-icon twitter'

  .copyright Active Bridge, LLC © 2013-2017. All Rights Reserved.

.left-pattern
.right-pattern